# Generated by Django 3.0.7 on 2020-06-28 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='biddate',
            field=models.DateField(default=datetime.date(2020, 6, 28)),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='bidet',
            field=models.TimeField(default=datetime.time(16, 11, 10)),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='bidst',
            field=models.TimeField(default=datetime.time(16, 11, 10)),
        ),
    ]
