# Generated by Django 3.0.7 on 2020-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbidding', '0003_auto_20200628_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='biddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='bidet',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='bidst',
            field=models.TimeField(null=True),
        ),
    ]
