# Generated by Django 3.0.7 on 2020-06-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productbidding', '0004_auto_20200628_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productbidding.Category'),
        ),
    ]
