# Generated by Django 3.0.7 on 2020-07-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbidding', '0007_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
