# Generated by Django 3.0.7 on 2020-07-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbidding', '0009_bidentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidentry',
            name='amount',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
