# Generated by Django 3.0.7 on 2020-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbidding', '0013_bidwinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidwinner',
            name='product_id',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bidwinner',
            name='useremail',
            field=models.CharField(max_length=100),
        ),
    ]
