# Generated by Django 3.0.7 on 2020-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbidding', '0014_auto_20200723_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidwinner',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
