# Generated by Django 3.0.7 on 2020-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbidding', '0015_auto_20200723_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidwinner',
            name='amount',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bidentry',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
