# Generated by Django 3.0.7 on 2020-07-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbidding', '0016_auto_20200723_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidwinner',
            name='bidtime',
            field=models.DateTimeField(null=True),
        ),
    ]
